<?php

namespace AppBundle\Repository;

/**
 * userAdressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class userAdressRepository extends \Doctrine\ORM\EntityRepository
{
}
